import Head from 'next/head'
import Roulette from '../components/roulette'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import dynamic from 'next/dynamic'

// const Odometer = dynamic(import('react-odometerjs'), {
//     ssr: false,
//     loading: () => 0
// });

export default function Home() {

  return (
    <div className={styles.container}>
      <Head>
        <title>ガチャバケーション</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          ガチャバケーション
        </h1>
        <section>
          <Roulette />
        </section>
      </main>
    </div>
  )
}
